import type { Metadata } from "next";
import "./globals.scss";
export const metadata: Metadata = {
  title: "Mabongpapa Shorts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        {children}
      </body>
    </html>
  );
}
