import type { Metadata } from "next";
import "./globals.scss";
export const metadata: Metadata = {
    title: "Mabongpapa Shorts",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <head>
                <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
            </head>
            <body>
                {children}
            </body>
        </html>
    );
}
